services:
  db:
    image: postgres:15.3
    container_name: nest-postgres
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-backend
    env_file:
      - ./.env
    ports:
      - "${PORT}:3000"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: spa-frontend-prod
    ports:
      - "5173:4173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000

volumes:
  pgdata: